services:
  application:
    image: localhost/goshortner
    ports:
      - "5555:5555"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    hotname: mongodb
    ports:
      - "27017:27017"

